# Hardware configuration placeholder
# This file is auto-generated by nixos-generate-config during installation
# Replace this with actual hardware-configuration.nix after running:
#   nixos-generate-config --root /mnt

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Example configuration - replace with actual hardware after install
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];  # kvm-intel or kvm-amd added at install time
  boot.extraModulePackages = [ ];

  # Filesystems - replace with actual UUIDs after partitioning
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;

  # Platform is set by flake, microcode handled at install time
}
